### ISSUE TITLE
Why is the same network added twice ?

### ISSUE THREAD

**Issue by Shubhamcl** [kkanshul/RelativeAttributes#1]
Hello,

In the file construct_network.lua, line 122 onwards, why is the network cloned and added again to the same nn.sequential block ?

`siamese_1=siamese_1:cuda()`
`parameters,gradParameters = siamese_1:getParameters()`
`siamese_2=siamese_1:clone('weight','bias','gradWeight','gradBias')`
`siamese_net:add(siamese_1)`
`siamese_net:add(siamese_2)`

**Comment by kkanshul** [comment]
Hi,

As network take pair of images as input , you need two branches with shared weights(siamese network). Hence we create a clone of the network and add it to a parallelTable.

**Comment by Shubhamcl** [comment]
Great, thanks for the response !
